steps:
  - id: "build"
    name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -f
      - cloud-run/nounify/Dockerfile
      - -t
      - "asia-northeast1-docker.pkg.dev/mztn-compute/container-images/nounify:$COMMIT_SHA"
      - cloud-run/nounify/
images:
  - "asia-northeast1-docker.pkg.dev/mztn-compute/container-images/nounify:$COMMIT_SHA"
options:
  logging: CLOUD_LOGGING_ONLY
